artifacts_root: artifacts 


data_ingestion:
  root_dir: artifacts/data_ingestion    #Directory for storing ingested data.
  source_URL: https://github.com/hrishipatil18/datasets/raw/refs/heads/main/winequality-data.zip   # Link to download the dataset.
  local_data_file: artifacts/data_ingestion/data.zip #Path for storing the downloaded file.
  unzip_dir: artifacts/data_ingestion  #Directory to extract the dataset.

data_validation:
  root_dir: artifacts/data_validation #Directory for storing validated data.
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv # The path to the dataset (winequality-red.csv) after data ingestion.
  STATUS_FILE: artifacts/data_validation/status.txt # A file where the validation status (e.g., success/failure) is logged.

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv #The path to the dataset (winequality-red.csv) after data ingestion.

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation  # main directory containing outputs of different pipeline stages.
  test_data_path: artifacts/data_transformation/test.csv # Specifies the path to the test dataset used for evaluating the model.
  model_path: artifacts/model_trainer/model.joblib # Points to the trained model file stored in the model training stage.
  metric_file_name: artifacts/model_evaluation/metrics.json # Stores the evaluation metrics (accuracy, precision, recall, RMSE, etc.) in JSON format.
